### ISSUE TITLE
How did you create glove6b_init_objects/attributes_300d.npy?

### ISSUE THREAD

**Issue by tihartmann** [jialinwu17/Self_Critical_VQA#8]
I am trying to recreate the glove embeddings for a different set of objects and attributes. Would you be able to share the code for creating the glove6b_init_objects_300d.npy and glove6b_init_attributes_300d.npy files? Thank you!

**Comment by alice-cool** [comment]
学者您解决了吗？有train36百度云盘的下载链接吗？打扰您了
